# Generated by Django 5.2.7 on 2025-11-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='module_index_map',
            field=models.JSONField(default=dict),
        ),
    ]
